### PR TITLE
WIP: Implement ilab experimental sample

### PR DESCRIPTION
**Pull request by thepetk**
Adds an MVP version of a new experimental sample using `terminado` & `ilab` to serve the `ilab model chat` command via a browser running terminal.

### CODE REVIEW

**Review by Jdubrick — COMMENTED** [review]
Is this a custom sample you made or an ai lab one?

**Comment by thepetk** [comment]
> Is this a custom sample you made or an ai lab one?

Is a new sample I made to have an ilab-chat sample.

**Comment by Jdubrick** [comment]
> > Is this a custom sample you made or an ai lab one?
> 
> Is a new sample I made to have an ilab-chat sample.

Do we know if the template changes related to this sample will be going to the main repo or experiment? Whatever one it is going to will need to be updated appropriately so it can pull in this sample and not break. I am thinking if the template changes are going to the main repo then this might need to go to `main` branch.

However if we want all custom samples to be under the `experiment` branch in this repo then handling will need to be done to pull it in the main repo (and handling done on the experiment repo to make sure it doesn't break also since experiment repo pulls in from this `experiment` branch for samples).

wdyt?
cc @redhat-ai-dev/ai-development-team

**Comment by thepetk** [comment]
> > > Is this a custom sample you made or an ai lab one?
> > 
> > 
> > Is a new sample I made to have an ilab-chat sample.
> 
> Do we know if the template changes related to this sample will be going to the main repo or experiment? Whatever one it is going to will need to be updated appropriately so it can pull in this sample and not break. I am thinking if the template changes are going to the main repo then this might need to go to `main` branch.
> 
> However if we want all custom samples to be under the `experiment` branch in this repo then handling will need to be done to pull it in the main repo (and handling done on the experiment repo to make sure it doesn't break also since experiment repo pulls in from this `experiment` branch for samples).
> 
> wdyt? cc @redhat-ai-dev/ai-development-team

This is pretty much why it's marked under WIP. I'm currently working on the experiment template PR. I'm expecting only a few updates. The current template has some items that can be excluded for the ilab sample. As we might still need further improvement or additional features for this sample too, I'm suggesting to add it first to the experiment branch and after having a structured approach, move it to main.

**Review by johnmcollier — COMMENTED** [review]
Just some food for thought:

Is this sample still going to target OpenShift AI/RHOAI? (Per the [AI Template plan](https://docs.google.com/spreadsheets/d/11S2h__-nN4fr25DJcfDbwQWXztLG5lrywthYPoSDPyQ/edit?gid=171758256#gid=171758256))

Browser-based apps are generally harder to run in an OpenShift AI workbench / JupyterLab-based environments, as it requires the end user to port forward the app's port to their machine. The OpenShift AI workbenches don't provide a browser that can access the app. Likewise, the workbenches all have a terminal with which ilab commands can be run, so the terminal web app isn't needed for RHOAI.

I'm wondering though... for an ilab based sample that's targeting OpenShift AI, do we need a traditional sample app? I wonder if it'd be better if we target just OpenShift AI (and not OpenShift) as a deployment target for ilab/instructlab. Perhaps just a sample repo that provides a Jupyter notebook walking the user through running ilab in RHOAI?

**Comment by thepetk** [comment]
> Is this sample still going to target OpenShift AI/RHOAI? (Per the [AI Template plan](https://docs.google.com/spreadsheets/d/11S2h__-nN4fr25DJcfDbwQWXztLG5lrywthYPoSDPyQ/edit?gid=171758256#gid=171758256))

> Browser-based apps are generally harder to run in an OpenShift AI workbench / JupyterLab-based environments. The OpenShift AI workbenches don't provide a browser that can access the app, so it requires the end user to port forward the app's port to their machine. However, the workbenches all provide a terminal with which ilab commands can be run, so the terminal web app isn't needed for RHOAI.

@johnmcollier the RHOAI + Jupyter Notebook + ilab should be a different one (for issue DEVHAS-703). This is an experiment on how it would look like if we had a very simple sample in order to run ilab on openshift.

> I wonder if it'd be better if we target just OpenShift AI (and not OpenShift) as a deployment target for ilab/instructlab and forgo a containerized app that needs to be built and deployed. I see value in running ilab through RHOAI, I'm not sure I see value in running it via standalone deployment in a web terminal. Perhaps we have just a simple repo that provides a Jupyter notebook walking the user through running ilab in RHOAI? And then in the template, don't deploy the app container for ilab, just the resources for RHOAI.

That's a very good point. I've tried to come this far with this sample only because I had some doubts if I'm missing something due to gap of knowledge.

Now that I've been testing with an actual sample, working with a custom template I can share the following:

* The setup of a software template like this (ilab deployed on openshift based on web based terminal using source taxonomy repository) is a very complicated one. Eventually this could be a hard-point for someone to use it as a starting point. Especially if we think about the persona type of the potential users.
* Marking this item as won't do and moving forward with the RHOAI one is a smart move. People who will look at ilab software template is quite more possible to be confident with Jupyter Notebooks & RHOAI workbenches than the openshift setup.
* Looking at the disk space that the suggested image takes it will be a very big deployment (>11gb) as ilab requires to download the model.

**Pull request closed without merging**
